server:
  port: 8080

spring:
  application:
    name: ssagri-ssakssak
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssagri?serverTimezone=UTC&characterEncoding=UTF-8
    username: supernova
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql : true

security:
  jwt:
    secret: sSaGrIsSaKsSaKsSaGr1sSaKsSaKsSaGrIsSaKsSaKsSaGr1sSaKsSaK
    expiration:
      access: 1800000    # 30 minutes in milliseconds
      refresh: 2592000000    # 30 days in milliseconds